#ifndef PLATFORMSPECIFIC_H
#define PLATFORMSPECIFIC_H

#include "androidusbdriver.h"
#define PLATFORM_ANDROID
#define _PLATFORM_DEPENDENT_USB_OBJECT androidUsbDriver
#define _PLATFORM_DEPENDENT_FOLDER_ACTION 

#endif // PLATFORMSPECIFIC_H
